services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ft-cl-db
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1435:1433"
    volumes:
      - fitness-db-data:/var/opt/mssql

volumes:
  fitness-db-data:
